/**
 * O Banco de Prompts da apostila.
 *
 * Os prompts prontos dos 12 capítulos, do Anexo A (por disciplina) e
 * do Guia de Bolso. Antes disto a plataforma tinha 3 — e nenhum
 * avulso: existiam só como subproduto das lições de prompt.
 *
 * As categorias são as do Anexo C, o índice que a própria apostila
 * usa para consulta rápida.
 *
 * Ficam de fora os prompts que a apostila mostra como ERRADOS para
 * contrastar com a versão boa: num banco de copiar-e-colar eles
 * seriam lidos como modelo, que é o erro que o curso combate.
 */

export const CATEGORIAS_PROMPT = {
  rotina: "Rotina e burocracia",
  planejamento: "Planejamento e BNCC",
  materiais: "Materiais e atividades",
  inclusao: "Inclusão e diferenciação",
  avaliacao: "Avaliação e feedback",
  etica: "Ética, LGPD e convivência",
  emergencias: "Emergências da rotina",
} as const;

export type CategoriaPrompt = keyof typeof CATEGORIAS_PROMPT;

export type PromptDoBanco = {
  titulo: string;
  corpo: string;
  categoria: CategoriaPrompt;
  disciplina: string | null;
  /** Onde está na apostila, para quem quiser ler o capítulo. */
  origem: string;
};

export const BANCO_PROMPTS: PromptDoBanco[] = [
  {
    titulo: "Ata de conselho de classe, exemplo pronto",
    corpo: "Reunião de conselho de classe, 8º ano A, 14/04/2026, 14h às 16h.\nPresentes: equipe gestora e professores da turma.\nPauta: rendimento em Português e Matemática; casos de infrequência.\nDecisões: grupo de estudos no contraturno para 5 alunos com\ndefasagem; 2 casos de infrequência encaminhados ao Conselho Tutelar;\nelogio formal à turma pela evolução no respeito.",
    categoria: "rotina",
    disciplina: null,
    origem: "Cap. 3.5",
  },
  {
    titulo: "Ata formal a partir de tópicos soltos",
    corpo: "Redija uma ata formal de reunião pedagógica com base nos tópicos\nabaixo:\n- Data: 15/05/2026, das 14h às 16h\n- Presentes: coordenadora, 3 professores (Matemática, Português,\n Ciências)\n- Pautas discutidas: baixo rendimento do 7ºB em matemática,\n proposta de reforço no contraturno, organização da Feira de\n Ciências (data: agosto), necessidade de compra de materiais\n- Decisões: reforço às terças e quintas, feira marcada para\n 20/08, lista de materiais será enviada à direção\n- Próxima reunião: 29/05/2026",
    categoria: "rotina",
    disciplina: null,
    origem: "Cap. 3.4",
  },
  {
    titulo: "Carta de recomendação para um aluno",
    corpo: "Escreva uma carta de recomendação para um aluno fictício do 9º\nano que está se candidatando a uma vaga em instituto federal.\nCaracterísticas: dedicado, curioso em ciências, participou da\nfeira de ciências, ajuda colegas com dificuldade, frequência\nexemplar. Tom: formal, mas caloroso e específico. Evite\ngeneralidades vazias.",
    categoria: "rotina",
    disciplina: null,
    origem: "Cap. 3.5",
  },
  {
    titulo: "Comunicado de evento para as famílias",
    corpo: "Escreva um comunicado formal, mas acolhedor, para os pais dos\nalunos do 3º ano sobre a Festa Junina da escola. Data: 28 de\njunho, sexta-feira, das 14h às 17h. Cada aluno deve trazer um\nprato típico. Alunos alérgicos devem informar a professora.\nIncluir número do telefone da escola para dúvidas: (XX) XXXX-XXXX.",
    categoria: "rotina",
    disciplina: null,
    origem: "Cap. 3.2",
  },
  {
    titulo: "Comunicado formal e acolhedor",
    corpo: "Escreva um comunicado formal, mas acolhedor, para os\nresponsáveis dos alunos do [ANO] sobre [EVENTO/ASSUNTO].\nInformações: [DATA, HORÁRIO, LOCAL, O QUE DEVEM LEVAR].\nUse linguagem clara e acessível, evitando termos burocráticos.\nMáximo 2 parágrafos. Termine com o telefone da escola para\ndúvidas.",
    categoria: "rotina",
    disciplina: null,
    origem: "Cap. 2.5",
  },
  {
    titulo: "Cronograma semanal de quem dá aula em muitas turmas",
    corpo: "Sou professor de Português e dou aulas para 5 turmas (6ºA, 6ºB,\n7ºA, 7ºB e 8ºA). Tenho 4 horas livres por semana (segunda 13h-15h\ne quarta 13h-15h). Preciso encaixar nessas horas: correção de\nredações do 8ºA (urgente), preparação de prova do 7ºA (para\nsexta), e preenchimento do diário de classe de todas as turmas.\nMonte meu cronograma otimizado em tabela, priorizando as tarefas\nmais urgentes. Garanta que nada seja levado para o fim de semana.",
    categoria: "rotina",
    disciplina: null,
    origem: "Cap. 3.1",
  },
  {
    titulo: "E-mail curto sobre faltas, com tom de parceria",
    corpo: "Escreva um e-mail curto e empático para a mãe de um aluno fictício\nde 12 anos, do 7º ano.\n\nContexto: ele é inteligente e participativo quando se interessa, mas\nnas últimas duas semanas conversou muito durante as explicações e\ndeixou de entregar duas tarefas.\n\nTom: convite à parceria entre escola e família — nunca punitivo.\nComece por algo positivo real sobre ele. Termine convidando para uma\nconversa presencial. Máximo 2 parágrafos curtos.",
    categoria: "rotina",
    disciplina: null,
    origem: "Cap. 3.3",
  },
  {
    titulo: "E-mail empático para a família",
    corpo: "Escreva um e-mail breve e empático para os responsáveis de um\naluno de [IDADE] anos. O assunto é: [DESCREVA A SITUAÇÃO]. O tom\ndeve ser de parceria, nunca punitivo. Termine convidando para uma\nconversa.",
    categoria: "rotina",
    disciplina: null,
    origem: "Cap. 2.5",
  },
  {
    titulo: "E-mail sobre comportamento, sem gerar atrito",
    corpo: "Escreva um e-mail empático para os pais de um aluno fictício de\n12 anos do 7º ano. Ele tem sido desrespeitoso com os colegas e se\nrecusou a fazer 3 atividades em sala esta semana. O tom deve ser\nde parceria escola-família, nunca punitivo. Mencione os pontos\npositivos dele (é inteligente e participativo quando quer).\nTermine convidando para uma conversa presencial.",
    categoria: "rotina",
    disciplina: null,
    origem: "Cap. 3.2",
  },
  {
    titulo: "Parecer de aluno do 2º ano, exemplo pronto",
    corpo: "Minhas anotações sobre aluno fictício de 7 anos, 2º ano:\n- Não reconhece todas as letras do alfabeto ainda\n- Falta muito às aulas (principalmente segundas)\n- Quando presente, é carinhoso e participativo\n- Gosta de desenhar e tem habilidade artística\n- Precisa de reforço individualizado em alfabetização\n\nTransforme em parecer descritivo. Tom: respeitoso, sem\njulgamento, focado nas potencialidades.",
    categoria: "rotina",
    disciplina: null,
    origem: "Cap. 3.3",
  },
  {
    titulo: "Parecer descritivo a partir de anotações",
    corpo: "Aja como um professor acolhedor. Transforme estas anotações em\ntópicos sobre um aluno fictício em um parecer descritivo\nbimestral de 1 parágrafo. Foque nos avanços, cite uma meta para o\npróximo bimestre. Anotações: [COLE SUAS NOTAS AQUI].",
    categoria: "rotina",
    disciplina: null,
    origem: "Cap. 2.5",
  },
  {
    titulo: "Parecer descritivo a partir de frases soltas",
    corpo: "Transforme minhas anotações abaixo em um parecer descritivo\nbimestral de 2 parágrafos, em tom acolhedor e profissional. Foque\nnos avanços. Termine com uma meta positiva para o próximo\nbimestre.\n\nAnotações sobre aluna fictícia de 9 anos, 3º ano:\n- Melhorou muito na leitura em voz alta este bimestre\n- Ainda troca algumas letras (p/b, t/d) na escrita\n- É muito prestativa, ajuda os colegas\n- Participativa nas rodas de conversa\n- Tem dificuldade em ficar parada por muito tempo\n- Adorou o projeto do Horário da Leitura",
    categoria: "rotina",
    disciplina: null,
    origem: "Cap. 3.3",
  },
  {
    titulo: "Parecer em tom acolhedor, começando pelos avanços",
    corpo: "Aja como coordenadora pedagógica experiente em avaliação formativa.\n\nVou enviar anotações soltas sobre vários alunos fictícios, um por vez.\nPara cada um, escreva um parecer descritivo de 2 parágrafos:\n- Tom acolhedor e profissional\n- Comece pelos avanços concretos\n- Aponte o que precisa de estímulo, sem julgamento\n- Termine com uma meta positiva para o próximo bimestre\n\nConfirme que entendeu e eu envio o primeiro.",
    categoria: "rotina",
    disciplina: null,
    origem: "Cap. 3.3",
  },
  {
    titulo: "Pedido formal à direção da escola",
    corpo: "Escreva um e-mail formal e respeitoso para a diretora da escola\nsolicitando a compra de 10 caixas de lápis de cor para o projeto\nde artes do 4º ano. Justifique a importância do material para o\ndesenvolvimento das atividades previstas no planejamento\nbimestral.",
    categoria: "rotina",
    disciplina: null,
    origem: "Cap. 3.2",
  },
  {
    titulo: "Relatório semestral da turma",
    corpo: "Escreva um relatório semestral de uma turma fictícia do 5º ano de\numa escola municipal, para ser enviado à Secretaria Municipal de\nEducação. Inclua: número de alunos (28), frequência média (87%),\nprincipais avanços (melhoria em leitura e interpretação),\ndificuldades (matemática: frações e geometria), projetos\nrealizados (Feira do Livro, Horta Escolar), necessidades (sala de\ninformática e material de educação física).",
    categoria: "rotina",
    disciplina: null,
    origem: "Cap. 3.5",
  },
  {
    titulo: "Atividade de Matemática com contexto da turma",
    corpo: "Aja como uma professora de Matemática do 4º ano. Crie uma atividade de\n30 minutos sobre multiplicação por 2 e por 3, usando situações do\ncotidiano de uma criança que mora em cidade pequena (ir à padaria,\ncontar ovos na granja). A atividade deve ter: (1) um texto motivador\ncurto, (2) 5 exercícios com grau crescente de dificuldade, (3) um\ndesafio bônus para os alunos mais rápidos. Entregue tudo formatado e\npronto para imprimir.",
    categoria: "planejamento",
    disciplina: null,
    origem: "Cap. 2.3",
  },
  {
    titulo: "Aula de Rotação por Estações sobre pontuação",
    corpo: "Monte uma aula de Rotação por Estações sobre \"Pontuação (ponto,\nvírgula, exclamação, interrogação)\" para o 4º ano.\n\nEstação 1 (Leitura): Textos com pontuação errada para o aluno\ncorrigir.\nEstação 2 (Jogo): Jogo de cartas onde o aluno combina a frase com\no sinal correto.\nEstação 3 (Escrita): O aluno escreve 5 frases usando todos os\nsinais.\nEstação 4 (Tecnologia): Se houver computador, sugira um site\ngratuito. Se não houver, proponha uma atividade alternativa.\n\nDetalhe cada estação com materiais e instruções.",
    categoria: "planejamento",
    disciplina: null,
    origem: "Cap. 4.4",
  },
  {
    titulo: "Aula por Rotação por Estações",
    corpo: "Crie uma aula usando a metodologia de Rotação por Estações para\n[DISCIPLINA], [ANO], tema [TEMA]. Planeje 4 estações de 12\nminutos cada, com atividades diferentes (leitura, jogo, escrita e\ndiscussão). Liste os materiais de cada estação.",
    categoria: "planejamento",
    disciplina: null,
    origem: "Cap. 2.5",
  },
  {
    titulo: "Conteúdo transformado em jogo",
    corpo: "Transforme o conteúdo de \"Tabuada do 6 ao 9\" em um jogo de\ncompetição entre equipes para alunos do 5º ano. Inclua: regras,\nsistema de pontuação, perguntas-desafio (15 perguntas com\nrespostas), e uma premiação simbólica para a equipe vencedora\n(ex: escolher a brincadeira do recreio).",
    categoria: "planejamento",
    disciplina: null,
    origem: "Cap. 4.4",
  },
  {
    titulo: "Detalhar um item do esqueleto",
    corpo: "Agora detalhe o item 3 do esqueleto acima (a atividade prática).\nInclua materiais necessários e tempo estimado.",
    categoria: "planejamento",
    disciplina: null,
    origem: "Cap. 2.4",
  },
  {
    titulo: "Encontrar a habilidade certa da BNCC",
    corpo: "\"Quais são as habilidades de Ciências do 7º ano relacionadas a\nsustentabilidade? Liste o código e a descrição de cada uma.\"\n\n\"O que este documento orienta sobre a avaliação na Educação\nInfantil?\"\n\n\"Crie 5 perguntas de interpretação baseadas nas páginas 45 a 52.\"\n\n\"Resuma o capítulo 3 em tópicos que eu possa usar como roteiro\nde aula.\"",
    categoria: "planejamento",
    disciplina: null,
    origem: "Cap. 5.1",
  },
  {
    titulo: "Esqueleto do plano de aula, para detalhar depois",
    corpo: "Crie o esqueleto (apenas os títulos e subtítulos) de um plano de\naula sobre Independência do Brasil para o 7º ano.",
    categoria: "planejamento",
    disciplina: null,
    origem: "Cap. 2.4",
  },
  {
    titulo: "Plano B quando o recurso falha",
    corpo: "Eu ia dar uma aula sobre [TEMA] para o [ANO] usando [RECURSO QUE\nFALHOU: projetor / internet / laboratório]. Isso não vai ser\npossível hoje. Crie uma aula alternativa de 50 minutos sobre o\nmesmo tema, usando apenas lousa, giz e o caderno dos alunos.\nDê o passo a passo cronometrado.",
    categoria: "planejamento",
    disciplina: null,
    origem: "Cap. 2.5",
  },
  {
    titulo: "Plano de aula completo",
    corpo: "Aja como professor(a) de [DISCIPLINA] do [ANO]. Crie um plano de\naula de 50 minutos sobre [TEMA]. Inclua: objetivo de\naprendizagem, habilidade BNCC relacionada, materiais necessários\n(de baixo custo), passo a passo cronometrado, e uma atividade de\nfechamento.",
    categoria: "planejamento",
    disciplina: null,
    origem: "Cap. 2.5",
  },
  {
    titulo: "Plano de aula cronometrado, passo a passo",
    corpo: "Aja como um professor de Ciências do 7º ano com 15 anos de\nexperiência. Crie um plano de aula de 50 minutos sobre \"Estados\nFísicos da Matéria (sólido, líquido e gasoso)\". Minha escola é\npública e não tem laboratório de ciências, então a atividade\nprática deve usar materiais de baixo custo (gelo, água, vela,\npanela).\n\nEstruture o plano assim:\n1. Tema e habilidade BNCC\n2. Objetivo de aprendizagem\n3. Materiais necessários (com quantidades)\n4. Desenvolvimento da aula dividido em momentos cronometrados:\n - Acolhida e motivação (5 min)\n - Explicação teórica (15 min)\n - Atividade prática demonstrativa (15 min)\n - Discussão e registro no caderno (10 min)\n - Fechamento e tarefa de casa (5 min)\n5. Avaliação: como saber se os alunos aprenderam\n6. Plano B: o que fazer se a atividade prática não funcionar",
    categoria: "planejamento",
    disciplina: null,
    origem: "Cap. 4.1",
  },
  {
    titulo: "Plano de aula de Ciências, exemplo completo",
    corpo: "Aja como professor de Ciências do 6º ano. Crie um plano de aula de\n50 minutos sobre Sistema Solar para amanhã de manhã.\n\nRestrições reais: sem projetor, sem internet na sala, apenas lousa,\ngiz e o caderno dos alunos. Turma de 32 alunos, agitada no primeiro\nhorário.\n\nEntregue: (1) uma abertura de 5 min que capture a atenção, (2)\nexplicação com um desenho que eu consiga reproduzir na lousa,\n(3) uma atividade em duplas, (4) fechamento com registro no caderno.\nCronometre cada momento.",
    categoria: "planejamento",
    disciplina: null,
    origem: "Cap. 2.5",
  },
  {
    titulo: "Plano no modelo exato que a escola usa",
    corpo: "Vou colar abaixo um modelo de plano de aula que minha escola usa.\nCrie um novo plano seguindo EXATAMENTE essa mesma estrutura e\nformatação, mas sobre o tema \"Ciclo da Água\" para o 5º ano.\n\nMODELO: [COLE AQUI O SEU MODELO]",
    categoria: "planejamento",
    disciplina: null,
    origem: "Cap. 2.4",
  },
  {
    titulo: "Projeto de 2 semanas unindo duas disciplinas",
    corpo: "Crie um projeto interdisciplinar de 2 semanas unindo Ciências e\nMatemática para o 5º ano sobre resíduos na escola.\n\nRESTRIÇÕES REAIS (respeite todas):\n- Verba: R$ 0. Só materiais que os alunos já têm ou lixo reciclável\n- Eu não tenho horário comum com o professor de Matemática: o\n projeto precisa funcionar com eu sozinho conduzindo as duas frentes\n- 4 aulas no total, de 50 min, dentro do meu horário normal\n- A escola não tem pátio disponível durante a aula\n\nEntregue: objetivo por aula, o que o aluno faz em cada uma, produto\nfinal exposto no corredor, e critérios de avaliação em rubrica.",
    categoria: "planejamento",
    disciplina: null,
    origem: "Cap. 4.2",
  },
  {
    titulo: "Projeto interdisciplinar de 3 semanas",
    corpo: "Crie um projeto interdisciplinar de 3 semanas para o 4º ano\nconectando Matemática e Ciências. Tema: \"A Horta Escolar\".\n\nO projeto deve incluir:\n- Justificativa pedagógica\n- Objetivos de Matemática (medidas, gráficos) e de Ciências\n (germinação, solo, água)\n- Habilidades BNCC de ambas as disciplinas\n- Cronograma semanal (semanas 1, 2 e 3)\n- Lista de materiais\n- Produto final dos alunos (relatório com gráficos do crescimento\n das plantas)\n- Critérios de avaliação",
    categoria: "planejamento",
    disciplina: null,
    origem: "Cap. 4.3",
  },
  {
    titulo: "Projeto interdisciplinar entre duas disciplinas",
    corpo: "Crie um projeto interdisciplinar que conecte [DISCIPLINA 1] e\n[DISCIPLINA 2] sobre o tema [TEMA] para o [ANO]. Duração: [X\nsemanas]. Inclua: justificativa, objetivos, cronograma semanal,\nproduto final dos alunos e critérios de avaliação.",
    categoria: "planejamento",
    disciplina: null,
    origem: "Cap. 2.5",
  },
  {
    titulo: "Roteiro de Sala de Aula Invertida",
    corpo: "Crie um roteiro de Sala de Aula Invertida para o tema \"Revolução\nIndustrial\" no 8º ano.\n\nParte 1 (Casa): Sugira que tipo de vídeo curto (até 8 min) os\nalunos devem assistir e crie 3 perguntas de pré-aula para eles\nresponderem.\nParte 2 (Sala): Planeje uma atividade prática de 50 min onde os\nalunos, em grupos, simulem a criação de uma fábrica têxtil usando\nmateriais simples. Descreva passo a passo.",
    categoria: "planejamento",
    disciplina: null,
    origem: "Cap. 4.4",
  },
  {
    titulo: "Sequência didática de 5 aulas",
    corpo: "Elabore uma sequência didática de 5 aulas (50 min cada) sobre\n\"Água: Ciclo, Importância e Preservação\" para o 5º ano.\n\nPara cada aula, inclua:\n- Título da aula\n- Habilidade BNCC\n- Objetivo específico\n- Metodologia (aula expositiva, prática, debate, etc.)\n- Atividade do aluno\n- Forma de avaliação daquela aula\n\nA Aula 5 deve ser uma apresentação dos alunos sobre o que\naprenderam.",
    categoria: "planejamento",
    disciplina: null,
    origem: "Cap. 4.2",
  },
  {
    titulo: "Sequência didática de várias aulas",
    corpo: "Elabore uma sequência didática de [NÚMERO] aulas sobre [TEMA]\npara o [ANO]. Para cada aula, detalhe: objetivo, duração,\nmetodologia, atividade prática, forma de avaliação. Vincule cada\naula a uma habilidade da BNCC.",
    categoria: "planejamento",
    disciplina: null,
    origem: "Cap. 2.5",
  },
  {
    titulo: "Três planos de aula ruins e o que há de errado",
    corpo: "Me dê 3 exemplos de planos de aula RUINS sobre Reciclagem (com\nerros clássicos de planejamento) e, para cada um, explique o que\nestá errado e como corrigir.",
    categoria: "planejamento",
    disciplina: null,
    origem: "Cap. 2.4",
  },
  {
    titulo: "Arte com material reciclável",
    corpo: "Crie uma proposta de Arte para o [ANO] sobre [TEMA/MOVIMENTO\nARTÍSTICO] usando apenas materiais de baixo custo ou recicláveis.\nInclua: breve contextualização do movimento em linguagem\nacessível, passo a passo da produção, e uma proposta de exposição\ndos trabalhos na escola. Vincule à habilidade da BNCC.",
    categoria: "materiais",
    disciplina: "Educação Física e Arte",
    origem: "Educação Física e Arte",
  },
  {
    titulo: "Atividade a partir de fonte histórica",
    corpo: "Crie uma atividade sobre [PERÍODO/EVENTO] para o [ANO] a partir\nda análise de uma fonte histórica. Elabore um trecho fictício mas\nhistoricamente plausível de [carta / notícia de jornal da época /\nrelato], deixando claro que é uma reconstrução didática. Depois\ncrie 4 perguntas que levem o aluno a interpretar a fonte, não a\ndecorar datas.",
    categoria: "materiais",
    disciplina: "História e Geografia",
    origem: "História e Geografia",
  },
  {
    titulo: "Atividade para adultos da EJA",
    corpo: "Aja como professor(a) de EJA. Crie uma atividade sobre [TEMA]\npara alunos adultos que retomaram os estudos. Considere:\n- Eles trazem muita experiência de vida e trabalho — aproveite\n isso como ponto de partida\n- Não infantilize a linguagem nem os exemplos\n- Contextualize com situações do mundo do trabalho, direitos,\n documentos e vida prática\n- O tempo deles é escasso: a atividade deve caber em 40 minutos\nInclua uma discussão inicial que valorize o que eles já sabem.",
    categoria: "materiais",
    disciplina: "EJA",
    origem: "EJA (Educação de Jovens e Adultos)",
  },
  {
    titulo: "Aula com material que já existe na escola",
    corpo: "Crie uma aula de 50 minutos sobre [CONTEÚDO] para o [ANO] usando\napenas materiais que eu tenha em casa ou na escola (tampinhas,\npalitos, papel, barbante, caixas de ovo). Detalhe o passo a\npasso, o que o professor fala e o que os alunos fazem em cada\nmomento.",
    categoria: "materiais",
    disciplina: "Matemática",
    origem: "Matemática",
  },
  {
    titulo: "Brincadeiras de consciência fonológica",
    corpo: "Crie 5 brincadeiras de consciência fonológica para crianças em\nprocesso de alfabetização, trabalhando [rimas / sílabas /\nfonema inicial]. Cada brincadeira deve durar até 10 minutos, usar\nmateriais simples e poder ser feita em roda. Explique as regras\nem linguagem que eu possa falar diretamente para as crianças.",
    categoria: "materiais",
    disciplina: "Educação Infantil",
    origem: "Educação Infantil e Alfabetização",
  },
  {
    titulo: "Cartaz A3 para o mural da escola",
    corpo: "No Canva, crie um cartaz tamanho A3 para o mural da escola sobre\n\"Regras de Convivência da Turma do 3º Ano\". Use cores vibrantes,\nícones de crianças, e organize as regras em formato de lista\nnumerada com ilustrações. As regras devem ser: 1) Respeitar os\ncolegas, 2) Levantar a mão para falar, 3) Cuidar dos materiais da\nescola, 4) Ser gentil, 5) Ouvir com atenção.",
    categoria: "materiais",
    disciplina: null,
    origem: "Cap. 8.2",
  },
  {
    titulo: "Caça-palavras temático",
    corpo: "Crie um caça-palavras com 12 palavras relacionadas ao tema\n\"Sistema Solar\" para o 5º ano. Liste as palavras escondidas,\nforneça dicas para cada palavra (ex: \"Planeta vermelho conhecido\ncomo o vizinho da Terra\" = MARTE), e monte a grade 15x15 com as\nletras (usando formato de texto).",
    categoria: "materiais",
    disciplina: null,
    origem: "Cap. 6.3",
  },
  {
    titulo: "Cruzadinha educativa",
    corpo: "Crie uma cruzadinha educativa com 10 palavras sobre\n\"Independência do Brasil\" para o 7º ano. Para cada palavra,\nescreva uma dica contextualizada (não vale simplesmente\n\"sinônimo de...\"). Numere as dicas em \"Horizontal\" e \"Vertical\".",
    categoria: "materiais",
    disciplina: null,
    origem: "Cap. 6.3",
  },
  {
    titulo: "Debate estruturado",
    corpo: "Monte um debate estruturado para o [ANO] sobre [TEMA POLÊMICO\nADEQUADO À IDADE]. Inclua: contextualização para os alunos, 3\nargumentos consistentes para cada lado, regras de fala e escuta,\npapéis (mediador, debatedores, plateia com registro), e uma\natividade de síntese final onde cada aluno escreve sua posição\ncom justificativa.",
    categoria: "materiais",
    disciplina: "História e Geografia",
    origem: "História e Geografia",
  },
  {
    titulo: "Divulgação científica para adolescentes",
    corpo: "Aja como um divulgador científico que conversa com adolescentes.\nExplique [TEMA] para alunos do [ANO] usando como metáfora algo\nque eles conhecem bem (videogame, futebol, redes sociais ou\nmúsica). Mantenha o rigor do conteúdo, mas troque todos os\nexemplos abstratos por situações concretas. Ao final, inclua 3\nperguntas de interpretação e uma proposta de desenho ou esquema.",
    categoria: "materiais",
    disciplina: null,
    origem: "Cap. 2.5",
  },
  {
    titulo: "Divulgação científica para crianças",
    corpo: "Aja como um divulgador científico jovem que conversa com crianças\ndo 5º ano. Escreva um texto de 3 parágrafos curtos explicando\n\"Energia Solar e Fotossíntese\".\n\nRegra de engajamento: use a metáfora de como as plantas\n\"recarregam a bateria\" ou \"fazem poções de energia\", como nos\njogos de videogame.\n\nAo final, inclua 3 perguntas rápidas de interpretação e uma\nproposta de desenho.",
    categoria: "materiais",
    disciplina: null,
    origem: "Cap. 6.1",
  },
  {
    titulo: "Educação Física sem quadra",
    corpo: "Crie uma aula de Educação Física de 50 minutos sobre [TEMA/\nHABILIDADE] para o [ANO], mas a quadra está ocupada e só tenho a\nsala de aula com as carteiras. Proponha atividades seguras\npossíveis nesse espaço, com aquecimento, parte principal e volta\nà calma. Inclua adaptações para alunos com mobilidade reduzida.",
    categoria: "materiais",
    disciplina: "Educação Física e Arte",
    origem: "Educação Física e Arte",
  },
  {
    titulo: "Experimento de baixo custo",
    corpo: "Crie um experimento demonstrativo sobre [TEMA] para o [ANO],\nusando apenas materiais de baixo custo encontrados em mercado ou\nem casa. Inclua: pergunta investigativa inicial, materiais com\nquantidades, passo a passo, o que os alunos devem observar e\nregistrar, explicação científica correta, e um plano B caso o\nexperimento não funcione.",
    categoria: "materiais",
    disciplina: "Ciências",
    origem: "Ciências da Natureza",
  },
  {
    titulo: "Explicar um conceito no tom de um youtuber",
    corpo: "Explique o que é fotossíntese como se você fosse um youtuber\nengraçado de 25 anos explicando para crianças de 8 anos. Use\npiadas, emojis e analogias com comida.",
    categoria: "materiais",
    disciplina: null,
    origem: "Cap. 2.4",
  },
  {
    titulo: "Geografia do território onde o aluno vive",
    corpo: "Crie uma atividade de Geografia para o [ANO] sobre [TEMA] que\nparta do território onde os alunos vivem: [descreva a região].\nOs alunos devem observar, registrar e comparar o que veem no\nbairro com o conceito estudado. Inclua um roteiro de observação\ne uma proposta de registro (mapa, desenho ou tabela).",
    categoria: "materiais",
    disciplina: "História e Geografia",
    origem: "História e Geografia",
  },
  {
    titulo: "Gramática a partir de texto real",
    corpo: "Crie uma atividade de [pontuação / concordância / classes\ngramaticais] para o [ANO], mas SEM exercícios soltos de completar\nlacunas. Use um texto real curto como base e peça que o aluno\nidentifique e justifique os usos dentro do texto. Inclua\ngabarito comentado explicando o raciocínio.",
    categoria: "materiais",
    disciplina: "Língua Portuguesa",
    origem: "Língua Portuguesa",
  },
  {
    titulo: "História curta para os anos iniciais",
    corpo: "Escreva uma história curta (2 páginas) para alunos do 3º ano\nsobre uma criança que descobre que a água do rio da sua cidade\nestá poluída e decide agir. A história deve ter: início, conflito\ne resolução. Use linguagem simples e diálogos entre os\npersonagens. Ao final, inclua 3 perguntas reflexivas sobre meio\nambiente.",
    categoria: "materiais",
    disciplina: null,
    origem: "Cap. 6.1",
  },
  {
    titulo: "Ilustração infantil para a atividade",
    corpo: "Crie uma ilustração infantil colorida, estilo cartoon, mostrando\numa criança de 8 anos com uniforme escolar plantando uma muda de\nárvore em um jardim da escola. A criança está sorrindo e usando\nluvas de jardinagem. O fundo mostra a escola ao longe.",
    categoria: "materiais",
    disciplina: null,
    origem: "Cap. 8.3",
  },
  {
    titulo: "Jogo de tabuleiro educativo",
    corpo: "Crie um jogo de tabuleiro educativo sobre [TEMA] para alunos do\n[ANO]. Inclua: regras do jogo, perguntas (com respostas),\nquantidade de jogadores, materiais necessários (apenas papel,\ntesoura, dados e lápis de cor).",
    categoria: "materiais",
    disciplina: null,
    origem: "Cap. 2.5",
  },
  {
    titulo: "Lista de exercícios com gabarito comentado",
    corpo: "Crie uma lista de 15 exercícios de Matemática sobre \"Adição e\nSubtração com Reagrupamento\" para o 3º ano.\n\nOrganize assim:\n- Exercícios 1 a 5: fáceis (números até 100)\n- Exercícios 6 a 10: médios (números até 500)\n- Exercícios 11 a 15: desafios (números até 1000, com situações-\n problema do cotidiano)\n\nInclua o gabarito completo ao final, com a resolução passo a\npasso dos exercícios de situação-problema.",
    categoria: "materiais",
    disciplina: null,
    origem: "Cap. 6.2",
  },
  {
    titulo: "Mapa mental para passar no quadro",
    corpo: "Crie a estrutura de um mapa mental sobre \"Cadeia Alimentar\" para\nalunos do 6º ano. O tema central é \"Cadeia Alimentar\". Os ramos\nprincipais devem ser: Produtores, Consumidores Primários,\nConsumidores Secundários, Consumidores Terciários,\nDecompositores. Para cada ramo, liste 3 exemplos de seres vivos\ncom uma descrição curta. Formate de modo que eu possa redesenhar\nno quadro ou montar no Canva.",
    categoria: "materiais",
    disciplina: null,
    origem: "Cap. 8.4",
  },
  {
    titulo: "Pacote de atividades para data comemorativa",
    corpo: "Crie um pacote de atividades para a Semana do Meio Ambiente\n(junho) para turmas do 1º ao 5º ano. Para cada ano, sugira: (1)\numa atividade prática de baixo custo, (2) um texto ou poema sobre\no tema adaptado à faixa etária, (3) uma proposta de atividade\nartística. O pacote deve funcionar como um mini-projeto de 1\nsemana.",
    categoria: "materiais",
    disciplina: null,
    origem: "Cap. 6.4",
  },
  {
    titulo: "Produção textual de um gênero",
    corpo: "Aja como professor(a) de Português do [ANO]. Crie uma proposta de\nprodução textual do gênero [crônica / carta de leitor / notícia /\nconto]. Inclua: texto motivador curto, comando claro da proposta,\ncritérios de avaliação em linguagem de aluno, e uma lista de\nverificação para o aluno revisar antes de entregar.",
    categoria: "materiais",
    disciplina: "Língua Portuguesa",
    origem: "Língua Portuguesa",
  },
  {
    titulo: "Quiz de verdadeiro ou falso",
    corpo: "Crie um quiz de 10 perguntas no estilo \"Verdadeiro ou Falso\"\nsobre higiene pessoal para alunos do 2º ano. Para cada afirmação\nfalsa, explique por que é falsa usando linguagem infantil.\nExemplo de formato: \"Afirmação: Lavar as mãos antes de comer não\né importante. (FALSO — Nossas mãos pegam muitos germes durante o\ndia...)\"",
    categoria: "materiais",
    disciplina: null,
    origem: "Cap. 6.3",
  },
  {
    titulo: "Resumo didático de um texto acadêmico",
    corpo: "Transforme o texto acadêmico abaixo em um resumo didático para\nalunos do [ANO]. Use linguagem acessível, analogias do cotidiano,\ne divida em tópicos com subtítulos. Ao final, crie 3 perguntas de\ncompreensão. Texto: [COLE O TEXTO AQUI].",
    categoria: "materiais",
    disciplina: null,
    origem: "Cap. 2.5",
  },
  {
    titulo: "Roteiro de podcast escolar",
    corpo: "Crie o roteiro de um podcast escolar de 5 minutos, apresentado\npor dois alunos do 8º ano, sobre \"Fake News e como identificá-\nlas\". Formato: diálogo natural entre os dois apresentadores, com\nfalas curtas. Inclua: vinheta de abertura, 3 dicas práticas de\nverificação, um exemplo real simplificado, e encerramento.\nIndique onde entram efeitos sonoros ou pausas.",
    categoria: "materiais",
    disciplina: null,
    origem: "Cap. 8.5",
  },
  {
    titulo: "Roteiro de vídeo educativo de 3 minutos",
    corpo: "Escreva o roteiro de um vídeo educativo de 3 minutos para o canal\nda escola sobre \"Por que a água é importante?\", voltado para\nalunos do 2º ao 5º ano. O roteiro deve ter: (1) abertura com uma\npergunta provocativa, (2) 3 curiosidades sobre a água, (3) 2\ndicas práticas de economia, (4) encerramento convidando os alunos\na fazer um desenho sobre o tema. Inclua indicações de\nimagens/cenas que devem aparecer em cada momento.",
    categoria: "materiais",
    disciplina: null,
    origem: "Cap. 8.5",
  },
  {
    titulo: "Sequência de uma semana na Educação Infantil",
    corpo: "Aja como professor(a) de Educação Infantil. Planeje uma sequência\nde atividades de 1 semana sobre [TEMA] para crianças de [IDADE]\nanos. Inclua para cada dia: acolhida, atividade principal (lúdica\ne com movimento), roda de conversa, e registro do que observar\nsobre o desenvolvimento das crianças. Considere que a turma tem\n[NÚMERO] crianças e uma professora.",
    categoria: "materiais",
    disciplina: "Educação Infantil",
    origem: "Educação Infantil e Alfabetização",
  },
  {
    titulo: "Situações-problema do cotidiano",
    corpo: "Aja como professor(a) de Matemática do [ANO]. Crie 8 situações-\nproblema sobre [CONTEÚDO] ambientadas no cotidiano de alunos de\n[descreva a realidade: zona rural / periferia urbana / cidade\npequena]. Evite contextos artificiais. Inclua resolução passo a\npasso de cada uma.",
    categoria: "materiais",
    disciplina: "Matemática",
    origem: "Matemática",
  },
  {
    titulo: "Texto com perguntas de dificuldade crescente",
    corpo: "Crie um texto de [GÊNERO] de 15 linhas sobre [TEMA] para o [ANO].\nDepois elabore 6 perguntas em ordem crescente de dificuldade:\n2 de localização de informação, 2 de inferência, 1 de opinião\njustificada e 1 que relacione o texto com a vida do aluno.",
    categoria: "materiais",
    disciplina: "Língua Portuguesa",
    origem: "Língua Portuguesa",
  },
  {
    titulo: "Texto informativo com a realidade da região",
    corpo: "Crie um texto informativo de 3 parágrafos sobre o Cerrado\nbrasileiro para alunos do 4º ano que moram em Goiás. Use nomes de\nanimais e frutas que eles encontram no dia a dia (pequi, buriti,\nlobo-guará, seriema). Ao final, inclua: (1) um glossário com 5\npalavras do texto, (2) 4 perguntas de interpretação, (3) uma\natividade de desenho (\"Desenhe o animal do texto que mais chamou\nsua atenção\").",
    categoria: "materiais",
    disciplina: null,
    origem: "Cap. 6.1",
  },
  {
    titulo: "Textos curtos para treinar fluência leitora",
    corpo: "Crie 5 textos curtíssimos (5 a 8 linhas) para treinar fluência\nleitora de um aluno fictício de 9 anos que lê com dificuldade e tem\nvergonha de ler em voz alta.\n- Vocabulário simples e repetitivo\n- Temas divertidos (animais, futebol, super-heróis)\n- Frases curtas, uma ideia por frase\n- Para cada texto: 2 perguntas com resposta localizada no texto\n- Tom que não infantilize: ele tem 9 anos, não 5",
    categoria: "materiais",
    disciplina: null,
    origem: "Cap. 6.4",
  },
  {
    titulo: "A mesma atividade em 3 níveis",
    corpo: "Crie a mesma atividade sobre [TEMA] em 3 versões para o [ANO]:\n\nVersão A (Básica): para alunos com defasagem. Texto curto,\nperguntas com resposta localizada diretamente no texto.\nVersão B (Intermediária): para alunos no nível esperado.\nPerguntas de interpretação.\nVersão C (Avançada): para alunos acima do nível. Perguntas de\ninferência, opinião e relação com outros temas.\n\nAs 3 versões devem ter o MESMO tema, para que a turma trabalhe\njunta sem que ninguém se sinta exposto.",
    categoria: "inclusao",
    disciplina: null,
    origem: "Cap. 2.5",
  },
  {
    titulo: "Concepções alternativas dos alunos",
    corpo: "Liste as 5 concepções alternativas (ideias erradas mas comuns)\nque alunos do [ANO] costumam ter sobre [TEMA]. Para cada uma,\nexplique por que ela surge e proponha uma pergunta ou\ndemonstração que provoque o conflito cognitivo necessário para\ncorrigi-la.",
    categoria: "inclusao",
    disciplina: "Ciências",
    origem: "Ciências da Natureza",
  },
  {
    titulo: "Desafios para alunos com altas habilidades",
    corpo: "Crie 3 \"Desafios do Mestre\" sobre o tema \"Frações Equivalentes\"\npara alunos do 5º ano com altas habilidades. Os desafios devem\nser problemas lógicos complexos que exijam raciocínio avançado,\nmas ainda usando o conteúdo de frações. Formato de enigma ou\nmistério matemático para motivá-los.",
    categoria: "inclusao",
    disciplina: null,
    origem: "Cap. 7.4",
  },
  {
    titulo: "Interpretação de texto com camada extra de desafio",
    corpo: "Crie uma atividade de interpretação de texto para o 5º ano sobre\n[TEMA], em 3 versões do MESMO texto:\n\nVersão A: texto de 5 linhas, perguntas com resposta localizada\ndiretamente no texto.\nVersão B: texto de 10 linhas, perguntas de interpretação.\nVersão C: texto de 15 linhas, perguntas de inferência e opinião.\n\nDepois, gere duas adaptações de FORMA da versão B:\n- Para dislexia: frases de até 10 palavras, ordem direta, sem\n fonemas parecidos, negrito nos nomes, espaçamento duplo.\n- Para TEA: linguagem 100% literal, sem metáforas, instruções\n numeradas passo a passo, checklist final.\n\nMantenha o MESMO tema e a mesma aparência visual em todas.",
    categoria: "inclusao",
    disciplina: null,
    origem: "Cap. 7.4",
  },
  {
    titulo: "Interpretação de texto em 3 níveis",
    corpo: "Crie a mesma atividade sobre \"Interpretação de Texto\" em 3\nversões para o 4º ano:\n\nVersão A (Básica): para alunos que ainda estão em processo de\nalfabetização. Texto de 5 linhas, perguntas com resposta\nlocalizada diretamente no texto.\n\nVersão B (Intermediária): para alunos no nível esperado. Texto de\n10 linhas, perguntas de interpretação.\n\nVersão C (Avançada): para alunos acima do nível. Texto de 15\nlinhas, perguntas de inferência e opinião.\n\nTodas as 3 versões devem ter o MESMO tema, para que a turma\ntrabalhe junta.",
    categoria: "inclusao",
    disciplina: null,
    origem: "Cap. 7.5",
  },
  {
    titulo: "Os 5 erros conceituais mais comuns",
    corpo: "Meus alunos do [ANO] estão errando sistematicamente em\n[CONTEÚDO]. Liste os 5 erros conceituais mais comuns que\nestudantes cometem nesse tópico, explique a causa de cada um, e\nproponha uma atividade curta para corrigir cada erro.",
    categoria: "inclusao",
    disciplina: "Matemática",
    origem: "Matemática",
  },
  {
    titulo: "Reforço de leitura fluente",
    corpo: "Tenho 5 alunos do 4º ano que ainda não dominam a leitura fluente.\nCrie 5 textos curtíssimos (5 a 8 linhas cada) com vocabulário\nsimples e repetitivo para treinar fluência. Os temas devem ser\ndivertidos (animais, super-heróis, comida). Para cada texto, crie\n2 perguntas simples de compreensão com respostas que podem ser\nencontradas diretamente no texto.",
    categoria: "inclusao",
    disciplina: null,
    origem: "Cap. 6.5",
  },
  {
    titulo: "Reforço para quem ainda não domina o conteúdo",
    corpo: "Tenho [NÚMERO] alunos do [ANO] que ainda não dominam [CONTEÚDO].\nCrie um material de reforço com: (1) uma explicação bem simples\ndo conceito, com um exemplo do cotidiano; (2) 5 exercícios do\nmais fácil ao mais difícil; (3) uma atividade prática manual.\nUse linguagem simples e frases curtas. Não use termos técnicos\nsem antes explicá-los.",
    categoria: "inclusao",
    disciplina: null,
    origem: "Cap. 2.5",
  },
  {
    titulo: "Texto difícil virado material de estudo",
    corpo: "Transforme o texto abaixo em um material de estudo para alunos do\n7º ano que têm dificuldade de leitura.\n\n- Troque TODA palavra difícil por uma simples (ou explique na hora)\n- Frases de no máximo 15 palavras\n- Divida em blocos com subtítulos que já digam a ideia principal\n- Use uma analogia do cotidiano para cada conceito abstrato\n- Ao final: um \"resumão\" de 5 tópicos e 3 perguntas de compreensão\n\nTexto: [COLE AQUI]",
    categoria: "inclusao",
    disciplina: null,
    origem: "Cap. 6.5",
  },
  {
    titulo: "Texto reescrito para outra idade de leitura",
    corpo: "Pegue o texto abaixo e reescreva para um aluno de [IDADE] anos\ncom [TDAH / Dislexia / TEA]. Use frases de no máximo 12 palavras,\ndestaque termos-chave em negrito, use listas numeradas e evite\nmetáforas. Texto: [COLE O TEXTO AQUI].",
    categoria: "inclusao",
    disciplina: null,
    origem: "Cap. 2.5",
  },
  {
    titulo: "A tarefa copiável, para comparar",
    corpo: "\"Faça uma pesquisa de 2 páginas sobre a Grécia Antiga\npara entregar na próxima semana.\"",
    categoria: "avaliacao",
    disciplina: null,
    origem: "Cap. 9.5",
  },
  {
    titulo: "Análise de redação com elogio e ajuste",
    corpo: "Aja como professor de Português experiente e acolhedor. Analise a\nredação abaixo de um aluno fictício do 9º ano.\n\nEstruture assim:\n1. O que o aluno fez BEM (seja específico, cite trechos dele)\n2. As 3 prioridades de melhoria — só três, as mais importantes\n (não liste todos os erros: isso paralisa)\n3. Para cada prioridade, mostre COMO melhorar reescrevendo um\n trecho dele como exemplo\n4. Uma frase final de encorajamento que seja verdadeira, não vazia\n\nTom: de quem quer que ele escreva de novo, não de quem está\njulgando. Nunca use ironia.",
    categoria: "avaliacao",
    disciplina: null,
    origem: "Cap. 9.4",
  },
  {
    titulo: "Avaliação diagnóstica de início de ano",
    corpo: "Crie uma avaliação diagnóstica de Matemática para ser aplicada no\nprimeiro dia de aula do 6º ano. O objetivo é descobrir quais\nconteúdos do 5º ano os alunos dominam e quais ainda têm lacunas.\nInclua questões sobre: operações básicas, frações simples,\ngeometria (formas), e interpretação de gráficos. Máximo 10\nquestões. Ao final, crie uma tabela de análise para eu marcar o\ndesempenho de cada aluno por habilidade.",
    categoria: "avaliacao",
    disciplina: null,
    origem: "Cap. 9.2",
  },
  {
    titulo: "Avaliação diagnóstica por níveis",
    corpo: "Aja como um professor elaborador de avaliações diagnósticas de\nMatemática. Crie 3 questões de múltipla escolha inéditas sobre\n\"Porcentagem no Comércio\" para o 7º ano.\n\nEstrutura de cada questão:\n- Enunciado contextualizado com o cotidiano de compras na feira\n ou supermercado\n- 4 alternativas (A, B, C, D), sendo apenas uma correta\n- Gabarito comentado explicando o cálculo correto\n- Análise das alternativas erradas: explique qual erro de\n raciocínio comum do aluno gerou cada alternativa incorreta",
    categoria: "avaliacao",
    disciplina: null,
    origem: "Cap. 6.2",
  },
  {
    titulo: "Feedback de redação que não desanima",
    corpo: "Aja como professor de Português. Vou colar a redação de um aluno\nfictício do 9º ano sobre \"Violência no trânsito\". Faça uma\nanálise construtiva apontando: (1) os pontos positivos (o que o\naluno fez bem), (2) os pontos a melhorar (erros de gramática,\nargumentação fraca, falta de conclusão), (3) sugestões práticas\nde como o aluno pode reescrever os trechos fracos. O tom deve ser\nencorajador, nunca humilhante.",
    categoria: "avaliacao",
    disciplina: null,
    origem: "Cap. 9.4",
  },
  {
    titulo: "Formulário de autoavaliação do aluno",
    corpo: "Crie um formulário de autoavaliação para alunos do 8º ano\nresponderem ao final do bimestre. Inclua perguntas como: \"O que\neu aprendi de mais importante?\", \"Qual foi minha maior\ndificuldade?\", \"Como eu avalio meu esforço de 1 a 5?\", \"O que\npretendo melhorar no próximo bimestre?\". Use linguagem acessível\npara adolescentes.",
    categoria: "avaliacao",
    disciplina: null,
    origem: "Cap. 9.2",
  },
  {
    titulo: "Prova com múltipla escolha e dissertativas",
    corpo: "Crie uma prova de [DISCIPLINA] para o [ANO] sobre [TEMA]. Inclua:\n5 questões de múltipla escolha (com 4 alternativas cada) e 2\nquestões dissertativas. As questões devem exigir interpretação,\nnão memorização. Forneça o gabarito comentado ao final.",
    categoria: "avaliacao",
    disciplina: null,
    origem: "Cap. 2.5",
  },
  {
    titulo: "Prova de História com fonte histórica",
    corpo: "Crie uma prova de História sobre a Revolução Francesa\npara o 8º ano com 10 questões.",
    categoria: "avaliacao",
    disciplina: null,
    origem: "Cap. 9.2",
  },
  {
    titulo: "Prova inédita que mede raciocínio",
    corpo: "Crie uma prova de Ciências para o 6º ano sobre \"Misturas\nHomogêneas e Heterogêneas\". Formato:\n- 5 questões de múltipla escolha com 4 alternativas cada\n- 2 questões dissertativas curtas\n- 1 questão \"desafio\" (opcional, vale ponto extra)\n\nREGRAS para as questões:\n- NÃO faça perguntas de decorar definições\n- Use situações do cotidiano (ex: fazer café, misturar suco em pó\n com água, separar feijão de pedrinhas)\n- As alternativas erradas devem ser plausíveis (não coloque\n opções absurdas)\n- Inclua gabarito comentado ao final, explicando POR QUE cada\n alternativa é certa ou errada",
    categoria: "avaliacao",
    disciplina: null,
    origem: "Cap. 9.1",
  },
  {
    titulo: "Rubrica de maquete",
    corpo: "Crie uma rubrica de avaliação para uma Maquete do Sistema Solar\n(Ciências, 5º ano). Critérios: Fidelidade Científica (os planetas\nestão na ordem certa?), Criatividade Visual, Trabalho em Equipe,\nApresentação Oral. Inclua 3 níveis de desempenho para cada\ncritério.",
    categoria: "avaliacao",
    disciplina: null,
    origem: "Cap. 9.3",
  },
  {
    titulo: "Rubrica de seminário",
    corpo: "Crie uma tabela de rubrica para avaliação de Seminário de\nHistória do 8º ano.\n\nCritérios (linhas): Domínio do Conteúdo, Clareza na Apresentação,\nUso de Recursos Visuais, Trabalho em Equipe, Respeito ao Tempo\n(10 min)\n\nNíveis (colunas): Excelente (10), Bom (7-9), Regular (5-6),\nInsuficiente (0-4)\n\nPara cada célula, descreva exatamente o que o aluno fez para\nmerecer aquela nota. Ex: \"Excelente em Domínio do Conteúdo = O\naluno respondeu todas as perguntas da plateia com segurança e\nacrescentou informações além do slide.\"",
    categoria: "avaliacao",
    disciplina: null,
    origem: "Cap. 9.3",
  },
  {
    titulo: "Tarefa à prova de cola: avaliar a resposta da IA",
    corpo: "Peça para a IA 3 argumentos a favor e 3 contra [TEMA]. Escolha o\nargumento que você achou mais forte, e venha preparado para\ndefendê-lo oralmente em 1 minuto na roda de conversa. Traga\nimpressa ou copiada a conversa que você teve com a IA.",
    categoria: "avaliacao",
    disciplina: null,
    origem: "Cap. 9.5",
  },
  {
    titulo: "Acordo de uso de IA com a turma",
    corpo: "Crie um \"Acordo de Uso Responsável de Inteligência Artificial\"\npara alunos do 8º e 9º ano. O documento deve ter linguagem\nacessível para adolescentes e incluir:\n1. O que é permitido: usar IA para pesquisar, tirar dúvidas, ter\n ideias\n2. O que NÃO é permitido: copiar respostas inteiras como se\n fossem suas, usar IA em provas\n3. A regra da transparência: sempre informar ao professor quando\n usou IA como auxílio\n4. O compromisso do senso crítico: sempre verificar se o que a IA\n disse é verdade\n5. Espaço para assinatura do aluno\n\nFormate como um documento bonito, com ícones e checkboxes.",
    categoria: "etica",
    disciplina: null,
    origem: "Cap. 10.5",
  },
  {
    titulo: "Relatório pedagógico sem dado identificável",
    corpo: "Aja como psicopedagoga. Escreva um relatório pedagógico de 3\nparágrafos para encaminhamento ao serviço de apoio.\n\nPerfil (fictício): estudante do 5º ano, com ausências frequentes no\nbimestre por questões de saúde, que mantém bom vínculo afetivo com\na turma e demonstra interesse quando presente. Apresenta defasagem\nem leitura decorrente das faltas.\n\nTom: técnico, respeitoso, focado em potencialidades e nas\nprovidências pedagógicas necessárias. Sem juízo de valor sobre a\nfamília.",
    categoria: "etica",
    disciplina: null,
    origem: "Cap. 10.2",
  },
  {
    titulo: "Aula vaga de última hora",
    corpo: "Preciso ocupar 50 minutos com o [ANO] agora, sem material\npreparado e sem saber o conteúdo em que eles estão.\n\nSugira 3 atividades independentes de conteúdo, que desenvolvam\nraciocínio, escrita ou trabalho em equipe, usando apenas papel e\nlápis. Para cada uma, explique as regras em 3 linhas.",
    categoria: "emergencias",
    disciplina: null,
    origem: "Cap. 12 · Guia de Bolso",
  },
  {
    titulo: "Conflito entre alunos",
    corpo: "Dois alunos fictícios do 6º ano tiveram um desentendimento sério\nno recreio e voltaram para a sala alterados.\n\nSugira um roteiro de mediação de conflito de 10 minutos que eu\npossa conduzir, com falas sugeridas, focado em escuta e acordo,\nsem expor nenhum dos dois diante da turma.",
    categoria: "emergencias",
    disciplina: null,
    origem: "Cap. 12 · Guia de Bolso",
  },
  {
    titulo: "O projetor quebrou",
    corpo: "Tenho 5 minutos para entrar na sala do 7º ano. Eu ia passar\nslides sobre o relevo brasileiro, mas o projetor queimou.\n\nCrie uma dinâmica prática e participativa usando apenas a lousa e\no caderno dos alunos sobre o mesmo tema. Dê um passo a passo para\neu conduzir os 50 minutos de aula com a sala engajada.",
    categoria: "emergencias",
    disciplina: null,
    origem: "Cap. 12 · Guia de Bolso",
  },
  {
    titulo: "Reunião de pais amanhã",
    corpo: "Tenho reunião de pais amanhã com a turma do [ANO] e ainda não\npreparei nada.\n\nMonte um roteiro de reunião de 40 minutos com: abertura\nacolhedora, 3 pontos principais a comunicar (avanços da turma,\ndificuldades gerais, combinados para o próximo bimestre), como\nconduzir perguntas difíceis, e um fechamento positivo. Inclua\nsugestões de fala.",
    categoria: "emergencias",
    disciplina: null,
    origem: "Cap. 12 · Guia de Bolso",
  },
  {
    titulo: "Substituição em matéria que não domino",
    corpo: "Fui chamado para cobrir uma aula de História no 8º ano agora e\nsou professor(a) de Matemática. O conteúdo indicado é \"Revolução\nIndustrial\".\n\nMe dê:\n1. Uma história curiosa de 3 minutos para abrir a aula e capturar\n a atenção da turma.\n2. Três perguntas provocativas para discutir em roda.\n3. Uma atividade rápida em dupla para os alunos escreverem no\n caderno nos últimos 20 minutos.",
    categoria: "emergencias",
    disciplina: null,
    origem: "Cap. 12 · Guia de Bolso",
  },
  {
    titulo: "Turma agitada voltando do recreio",
    corpo: "A turma do 5º ano voltou do recreio correndo, suada e falando\nmuito alto.\n\nSugira uma dinâmica de acolhimento e regulação de 5 minutos, sem\ngritos e sem bronca, focada em respiração lúdica e foco mental,\npara que possamos iniciar a aula em paz.",
    categoria: "emergencias",
    disciplina: null,
    origem: "Cap. 12 · Guia de Bolso",
  },
];
